<?php

namespace AppBundle\Repository;

/**
 * AttackUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackUnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
