<?php

namespace AppBundle\Repository;

/**
 * AttackUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackUnitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAttackUnits($attack, $status)
    {
        return $this->createQueryBuilder('u')
            ->where('u.attack = :attack')
            ->setParameter('attack', $attack)
            ->andWhere('u.status = :status')
            ->setParameter('status', $status)
            ->addOrderBy('u.id', 'ASC')
            ->getQuery()->execute();
    }
}
