<?php

namespace AppBundle\Repository;

/**
 * BattleReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleReportRepository extends \Doctrine\ORM\EntityRepository
{
}
