<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;

/**
 * BuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllBuildings()
    {
        return $this->createQueryBuilder('building')
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }

    public function getBuildingById($id)
    {
        return $this->createQueryBuilder('b')
            ->where('b.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute()[0];
    }
}
