<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Map;
use Doctrine\ORM\Query;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlayersOnMap()
    {
        return $this->createQueryBuilder('map')
            ->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
