<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Map;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends \Doctrine\ORM\EntityRepository
{

}
