<?php

namespace AppBundle\Repository;

/**
 * ProgressBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
