<?php

namespace AppBundle\Repository;

/**
 * ProgressResourcesExploreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressResourcesExploreRepository extends \Doctrine\ORM\EntityRepository
{
}
