<?php

namespace AppBundle\Repository;

/**
 * ProgressBuildingLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressBuildingLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
