<?php

namespace AppBundle\Repository;

/**
 * ProgressUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressUnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
