<?php

namespace AppBundle\Repository;

/**
 * ProgressResourcesRenewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressResourcesRenewRepository extends \Doctrine\ORM\EntityRepository
{
}
