<?php

namespace AppBundle\Repository;

/**
 * ProgressUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressUnitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnitsByStatus($user, $status)
    {
        return $this->createQueryBuilder('u')
            ->where('u.user = :user')
            ->setParameter('user',$user)
            ->andWhere('u.status = :status')
            ->setParameter('status', $status)
            ->getQuery()
            ->execute();
    }
}
