<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;

/**
 * ResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllResources()
    {
        return $this->createQueryBuilder('resources')->getAllAliases();
            //->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}

