<?php

namespace AppBundle\Repository;

/**
 * UserUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUnitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserUnitsByStatus($user, $status)
    {
        return $this->createQueryBuilder('u')
            ->where('u.status = :status')
            ->setParameter('status', $status)
            ->andWhere('u.user = :user')
            ->setParameter('user', $user)
            ->addOrderBy('u.id', 'ASC')
            ->getQuery()
            ->execute();
    }
}
