<?php

namespace AppBundle\Repository;

/**
 * UserUnitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUnitsRepository extends \Doctrine\ORM\EntityRepository
{
}
