<?php

namespace AppBundle\Repository;

/**
 * UserResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
