<?php

namespace AppBundle\Repository;

/**
 * UserBuildingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBuildingRepository extends \Doctrine\ORM\EntityRepository
{
}
