# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    attack_start:
            class: AppBundle\Service\AttackStartService
            arguments: ['@doctrine.orm.entity_manager']

    battle_report:
            class: AppBundle\Service\BattleService
            arguments: ['@doctrine.orm.entity_manager']

    buildings_service:
            class: AppBundle\Service\BuildingService
            arguments: ['@doctrine.orm.entity_manager']

    progress_service:
            class: AppBundle\Service\ProgressService
            arguments: ['@doctrine.orm.entity_manager']

    resources_service:
            class: AppBundle\Service\ResourcesService
            arguments: ['@doctrine.orm.entity_manager']

    user_service:
            class: AppBundle\Service\UserService
            arguments: ['@doctrine.orm.entity_manager']